Repository tensorwerk/hangar-py, pull requests merged in 2019-05, with the labels that each got.

#31 Multi-add docstring addition
  src/hangar/dataset.py
Labels: documentation

#40 Windows build appveyor config.
  appveyor.yml
  src/hangar/context.py
  src/hangar/records/parsing.py
  tests/conftest.py
  tests/test_checkout.py
Labels: Bug: Priority 3

#42 Removed manual disk space freeing
  appveyor.yml
  src/hangar/config_hangar.yml
Labels: Resolved, enhancement

#51 Empty dimension check
  src/hangar/records/parsing.py
  tests/test_dataset.py
Labels: Bug: Priority 2, WIP

#41 Invalidate existing dataset or metadata accessor objects after a checkout is closed
  setup.cfg
  setup.py
  src/hangar/checkout.py
  src/hangar/dataset.py
  src/hangar/metadata.py
  src/hangar/records/heads.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/test_checkout.py
  tests/test_dataset.py
  tests/test_metadata.py
Labels: Bug: Priority 1, Resolved

#52 fixed lock held check bug
  src/hangar/diff.py
Labels: Bug: Priority 3, Resolved

#25 Checkout testcases
  tests/conftest.py
  tests/test_checkout.py
Labels: WIP

#54 Fix invalidate obj on close
  src/hangar/checkout.py
  src/hangar/dataset.py
  src/hangar/metadata.py
  tests/test_checkout.py
  tests/test_dataset.py
Labels: Bug: Priority 2

#32 Merge & Diff Refactor
  setup.py
  src/hangar/checkout.py
  src/hangar/config_hangar.yml
  src/hangar/dataset.py
  src/hangar/diagnostics/ecosystem.py
  src/hangar/diff.py
  src/hangar/merger.py
  src/hangar/metadata.py
  src/hangar/records/commiting.py
  src/hangar/records/hashs.py
  src/hangar/records/heads.py
  src/hangar/records/parsing.py
  src/hangar/repository.py
  tests/conftest.py
  tests/test_checkout.py
  tests/test_dataset.py
  tests/test_initiate.py
  tests/test_merging.py
  tests/test_metadata.py
  tox.ini
Labels: Awaiting Review, Bug: Priority 2, enhancement

#57 Quick-Fix
  .bumpversion.cfg
  src/hangar/cli.py
  src/hangar/context.py
  src/hangar/diagnostics/graphing.py
  src/hangar/records/heads.py
  src/hangar/repository.py
  src/hangar/utils.py
Labels: Bug: Priority 3

#23 Added documentation discussing hangar core concepts
  README.rst
  docs/Hangar-Tutorial-001.rst
  docs/Hangar-Tutorial-002.rst
  docs/api.rst
  docs/concepts.rst
  docs/design.rst
  docs/index.rst
  docs/installation.rst
  docs/quickstart.rst
  docs/reference/hangar.rst
  docs/reference/index.rst
  docs/tutorial.rst
  docs/usage.rst
  src/hangar/checkout.py
  src/hangar/dataset.py
  src/hangar/metadata.py
Labels: documentation

#59 Bugfix - Remote repo fetch
  MANIFEST.in
  src/hangar/repository.py
  tox.ini
Labels: Bug: Priority 2, Resolved

#60 Exception Cleanup and Test Coverage
  src/hangar/dataset.py
  src/hangar/metadata.py
  tests/test_dataset.py
  tests/test_metadata.py
Labels: Bug: Priority 2, Resolved

#61 Created Changelog for Upcoming v0.1.0 Release
  AUTHORS.rst
  CHANGELOG.rst
  README.rst
Labels: Awaiting Review, documentation

#69 Update installation.rst
  docs/installation.rst
Labels: documentation, enhancement
