Repository tensorwerk/hangar-py, pull requests merged in 2019-10, with the labels that each got.

#124 Testing and Utils Improvements
  src/hangar/arrayset.py
  src/hangar/backends/selection.py
  src/hangar/cli/cli.py
  src/hangar/records/commiting.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_backend_heuristics.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_cli_io.py
Labels: Awaiting Review

#125 return branch heads in repo log method
  CHANGELOG.rst
  src/hangar/repository.py
  src/hangar/utils.py
  tests/test_visualizations.py
Labels: Awaiting Review, Bug: Priority 3

#128 Branch Deletion
  CHANGELOG.rst
  src/hangar/cli/cli.py
  src/hangar/records/commiting.py
  src/hangar/records/heads.py
  src/hangar/records/parsing.py
  src/hangar/records/queries.py
  src/hangar/records/summarize.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/test_branching.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_remotes.py
  tests/test_visualizations.py
Labels: Awaiting Review, WIP, enhancement

#130 Remotes Refactor
  setup.py
  src/hangar/constants.py
  src/hangar/context.py
  src/hangar/diagnostics/ecosystem.py
  src/hangar/records/commiting.py
  src/hangar/remote/chunks.py
  src/hangar/remote/client.py
  src/hangar/remote/config.py
  src/hangar/remote/config_server.ini
  src/hangar/remote/config_server.yml
  src/hangar/remote/content.py
  src/hangar/remote/hangar_service_pb2.py
  src/hangar/remote/hangar_service_pb2.pyi
  src/hangar/remote/header_manipulator_client_interceptor.py
  src/hangar/remote/request_header_validator_interceptor.py
  src/hangar/remote/server.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_dataloaders.py
  tests/test_diff.py
  tests/test_remote_serialize.py
  tests/test_remotes.py
  tox.ini
Labels: Awaiting Review, enhancement

#131 local data only arrayset iteration
  CHANGELOG.rst
  src/hangar/arrayset.py
  src/hangar/backends/__init__.py
  src/hangar/backends/selection.py
  src/hangar/checkout.py
  tests/test_arrayset.py
Labels: Awaiting Review, enhancement

#133 Dynamic Arrayset Backend Update and Manual Configuration of Filter Options
  .travis.yml
  CHANGELOG.rst
  src/hangar/__init__.py
  src/hangar/arrayset.py
  src/hangar/backends/__init__.py
  src/hangar/backends/hdf5_00.py
  src/hangar/backends/numpy_10.py
  src/hangar/backends/remote_50.py
  src/hangar/backends/selection.py
  src/hangar/dataloaders/common.py
  src/hangar/dataloaders/tfloader.py
  src/hangar/dataloaders/torchloader.py
  src/hangar/records/parsing.py
  src/hangar/remote/content.py
  src/hangar/remote/request_header_validator_interceptor.py
  src/hangar/remote/server.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_arrayset_backends.py
  tests/test_backend_hdf5_00.py
  tests/test_backend_heuristics.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_cli_io.py
  tests/test_initiate.py
  tests/test_remotes.py
Labels: Awaiting Review, enhancement

#147 hdf5_00 checksum calculation
  .travis.yml
  setup.py
  src/hangar/backends/hdf5_00.py
  src/hangar/backends/numpy_10.py
  src/hangar/backends/selection.py
  tests/test_backend_hdf5_00.py
Labels: Bug: Priority 1, Resolved

#150 Adding "status", "commit", and "create-arrayset" to CLI
  .coveragerc
  CHANGELOG.rst
  src/hangar/__init__.py
  src/hangar/arrayset.py
  src/hangar/backends/hdf5_00.py
  src/hangar/checkout.py
  src/hangar/cli/cli.py
  src/hangar/dataloaders/tfloader.py
  src/hangar/diagnostics/ecosystem.py
  src/hangar/diagnostics/graphing.py
  src/hangar/diff.py
  src/hangar/merger.py
  src/hangar/records/summarize.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_backend_hdf5_00.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_diff.py
  tests/test_diff_staged_summary.py
  tests/test_merging.py
  tests/test_remotes.py
  tests/test_utils.py
  tox.ini
Labels: Awaiting Review, enhancement

#151 Misc. Cleanups
  CHANGELOG.rst
  src/hangar/arrayset.py
  src/hangar/backends/hdf5_00.py
  src/hangar/context.py
  src/hangar/metadata.py
  src/hangar/records/parsing.py
  src/hangar/remotes.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_branching.py
  tests/test_dataloaders.py
  tests/test_merging.py
  tests/test_metadata.py
  tests/test_remotes.py
  tests/test_utils.py
Labels: Bug: Priority 3, Resolved

#134 Plugins revamp
  .readthedocs.yml
  CHANGELOG.rst
  docs/externals.rst
  docs/index.rst
  setup.py
  src/hangar/__main__.py
  src/hangar/cli/cli.py
  src/hangar/cli/io/__init__.py
  src/hangar/cli/io/_io.py
  src/hangar/cli/io/_plugins/__init__.py
  src/hangar/cli/io/_plugins/matplotlib_plugin.ini
  src/hangar/cli/io/_plugins/matplotlib_plugin.py
  src/hangar/cli/io/_plugins/pil_plugin.ini
  src/hangar/cli/io/_plugins/pil_plugin.py
  src/hangar/cli/io/manage_plugins.py
  src/hangar/cli/utils.py
  src/hangar/constants.py
  src/hangar/external/__init__.py
  src/hangar/external/_external.py
  src/hangar/external/base_plugin.py
  src/hangar/external/plugin_manager.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_cli.py
  tests/test_cli_io.py
  tests/test_cli_plugin.py
  tox.ini
Labels: Awaiting Review

#153 BUG FIX: Zero Valued Arrays Hash Incorrectly
  .gitignore
  src/hangar/arrayset.py
  src/hangar/remote/client.py
  src/hangar/remote/server.py
  tests/property_based/conftest.py
  tests/property_based/test_pbt_arrayset.py
  tests/property_based/test_pbt_metadata.py
  tests/test_arrayset.py
  tox.ini
Labels: Awaiting Review, Bug: Priority 1
