Repository tensorwerk/hangar-py, pull requests merged in 2019-11, with the labels that each got.

#156 Fix typos in tutorials / documentation
  AUTHORS.rst
  CHANGELOG.rst
  docs/Tutorial-001.ipynb
  docs/Tutorial-002.ipynb
  docs/Tutorial-003.ipynb
  docs/Tutorial-Dataloader.ipynb
  docs/backends.rst
  docs/cli.rst
  docs/concepts.rst
  docs/conf.py
  docs/design.rst
  docs/faq.rst
  docs/quickstart.rst
  src/hangar/cli/cli.py
  tests/property_based/conftest.py
  tests/property_based/test_pbt_arrayset.py
  tests/property_based/test_pbt_metadata.py
  tox.ini
Labels: documentation

#155 Benchmark Suite and Automated PR Regression Testing.
  .github/workflows/asvbench.yml
  .gitignore
  CHANGELOG.rst
  asv_bench/README.rst
  asv_bench/asv.conf.json
  asv_bench/benchmarks/__init__.py
  asv_bench/benchmarks/arrayset_data.py
  asv_bench/benchmarks/commit_and_checkout.py
  asv_bench/benchmarks/package.py
  docs/Tutorial-001.ipynb
  docs/Tutorial-003.ipynb
  docs/benchmarking.rst
  docs/contributingindex.rst
  docs/img/asv-detailed.png
  docs/img/asv-main.png
  docs/index.rst
  docs/noindexapi/apiinit.rst
  docs/noindexapi/apiremotefetchdata.rst
Labels: enhancement

#161 Namedtuple bugfix
  CHANGELOG.rst
  src/hangar/checkout.py
  tests/test_checkout_arrayset_access.py
Labels: Bug: Priority 3, Resolved

#159 BugFix: Removing All Samples in Arrayset Should Not Remove Aset Schema
  CHANGELOG.rst
  src/hangar/arrayset.py
  src/hangar/metadata.py
  src/hangar/records/hashmachine.py
  src/hangar/records/summarize.py
  src/hangar/remote/client.py
  src/hangar/remote/server.py
  src/hangar/repository.py
  tests/test_arrayset.py
  tests/test_checkout_arrayset_access.py
Labels: Bug: Priority 1, Resolved

#166 Bugfix - Write-Enabled checkout with commit argument raises exception
  CHANGELOG.rst
  src/hangar/repository.py
  tests/test_checkout.py
Labels: Bug: Priority 2

#165 added hash type codes
  CHANGELOG.rst
  docs/requirements_rtd.txt
  src/hangar/cli/cli.py
  src/hangar/records/commiting.py
  src/hangar/records/hashmachine.py
  src/hangar/records/parsing.py
  src/hangar/remote/server.py
  tests/conftest.py
  tests/property_based/test_pbb_valid_hash_tcodes.py
  tests/property_based/test_pbt_arrayset.py
  tests/property_based/test_pbt_metadata.py
  tests/test_commit_ref_verification.py
  tests/test_dataloaders.py
  tests/test_remote_serialize.py
  tox.ini
Labels: Awaiting Review

#170 Benchmark Update
  asv_bench/benchmarks/backend_comparisons.py
  asv_bench/benchmarks/backends/hdf5_00.py
  asv_bench/benchmarks/backends/hdf5_01.py
  asv_bench/benchmarks/backends/numpy_10.py
  asv_bench/benchmarks/commit_and_checkout.py
Labels: enhancement
