Repository tensorwerk/hangar-py, pull requests merged in 2019-07, with the labels that each got.

#82 fixed issue with docs not formatting code properly on rtd
  docs/Hangar-Tutorial-002.rst
Labels: Bug: Priority 3, documentation

#78 [BACKEND] Remote Server Updates for New Record Format
  .coveragerc
  .travis.yml
  README.rst
  ci/bootstrap.py
  codecov.yml
  setup.py
  src/hangar/backends/hdf5.py
  src/hangar/backends/np_mmap.py
  src/hangar/cli.py
  src/hangar/constants.py
  src/hangar/diagnostics/graphing.py
  src/hangar/records/heads.py
  src/hangar/records/parsing.py
  src/hangar/records/queries.py
  src/hangar/records/summarize.py
  src/hangar/remote/chunks.py
  src/hangar/remote/config.py
  src/hangar/remote/config_server.yml
  src/hangar/remote/generic_client_interceptor.py
  src/hangar/remote/hangar_client.py
  src/hangar/remote/hangar_server.py
  src/hangar/remote/hangar_service.proto
  src/hangar/remote/hangar_service_pb2.py
  src/hangar/remote/hangar_service_pb2_grpc.py
  src/hangar/remote/header_manipulator_client_interceptor.py
  src/hangar/remote/request_header_validator_interceptor.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_initiate.py
  tests/test_merging.py
  tests/test_remote.py
  tests/test_remotes.py
  tests/test_utils.py
  tests/test_visualizations.py
  tox.ini
Labels: Awaiting Review, Bug: Priority 2, enhancement

#84 multithread / multiprocess safe dataset reads
  CHANGELOG.rst
  src/hangar/backends/hdf5.py
  src/hangar/backends/np_mmap.py
  src/hangar/backends/remote_unknown.py
  src/hangar/backends/selection.py
  src/hangar/dataset.py
  tests/test_dataset.py
Labels: enhancement

#76 Testing new diff logic
  tests/conftest.py
  tests/test_diff.py
  tests/test_initiate.py
  tests/test_merging.py
Labels: Awaiting Review

#89 integer keys for dataset/metadata samples
  CHANGELOG.rst
  src/hangar/constants.py
  src/hangar/dataset.py
  src/hangar/metadata.py
  src/hangar/records/parsing.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_merging.py
  tests/test_metadata.py
Labels: Awaiting Review, enhancement

#85 WIP: Remote partial fetch/clone operations
  .coveragerc
  CHANGELOG.rst
  codecov.yml
  docs/Hangar-Tutorial-002.rst
  docs/api.rst
  docs/backends.rst
  docs/backends/hdf5_00.rst
  docs/backends/numpy_10.rst
  docs/backends/remote_50.rst
  docs/cli.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  mypy.ini
  scripts/run_proto_codegen.py
  setup.py
  src/hangar/__init__.py
  src/hangar/backends/__init__.py
  src/hangar/backends/hdf5_00.py
  src/hangar/backends/numpy_10.py
  src/hangar/backends/remote_50.py
  src/hangar/backends/remote_unknown.py
  src/hangar/backends/selection.py
  src/hangar/checkout.py
  src/hangar/cli.py
  src/hangar/context.py
  src/hangar/dataset.py
  src/hangar/diagnostics/ecosystem.py
  src/hangar/diff.py
  src/hangar/merger.py
  src/hangar/metadata.py
  src/hangar/records/commiting.py
  src/hangar/records/hashs.py
  src/hangar/records/heads.py
  src/hangar/records/parsing.py
  src/hangar/records/queries.py
  src/hangar/records/summarize.py
  src/hangar/remote/client.py
  src/hangar/remote/content.py
  src/hangar/remote/hangar_service_pb2.pyi
  src/hangar/remote/header_manipulator_client_interceptor.py
  src/hangar/remote/request_header_validator_interceptor.py
  src/hangar/remote/server.py
  src/hangar/remotes.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_backend_heuristics.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_dataset.py
  tests/test_initiate.py
  tests/test_remotes.py
  tests/test_visualizations.py
  tox.ini
Labels: WIP, enhancement

#99 Dataset iterator bugfix
  docs/api.rst
  docs/conf.py
  src/hangar/checkout.py
  src/hangar/dataset.py
  src/hangar/remotes.py
  src/hangar/repository.py
  tests/test_checkout.py
  tests/test_cli.py
  tests/test_dataset.py
Labels: Awaiting Review, Bug: Priority 2
