Repository tensorwerk/hangar-py, pull requests merged in 2019-08, with the labels that each got.

#94 Commit inside context manager
  .travis.yml
  README.rst
  docs/conf.py
  docs/design.rst
  src/hangar/checkout.py
  src/hangar/dataset.py
  src/hangar/diagnostics/ecosystem.py
  src/hangar/utils.py
  tests/conftest.py
  tests/test_checkout.py
  tests/test_diff.py
  tox.ini
Labels: Bug: Priority 1, Resolved

#100 License fixes
  src/hangar/diagnostics/ecosystem.py
  src/hangar/diagnostics/graphing.py
  src/hangar/records/summarize.py
  src/hangar/remote/config.py
  src/hangar/remote/header_manipulator_client_interceptor.py
  src/hangar/remote/request_header_validator_interceptor.py
  src/hangar/repository.py
  src/hangar/utils.py
  tests/test_utils.py
  tests/test_visualizations.py
Labels: Bug: Priority 3, Resolved

#91 Dataloaders for PyTorch & Tensorflow
  .travis.yml
  CHANGELOG.rst
  appveyor.yml
  ci/appveyor-bootstrap.py
  docs/api.rst
  docs/faq.rst
  setup.py
  src/hangar/__init__.py
  src/hangar/backends/selection.py
  src/hangar/dataloaders/__init__.py
  src/hangar/dataloaders/common.py
  src/hangar/dataloaders/tfloader.py
  src/hangar/dataloaders/torchloader.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_dataloaders.py
  tox.ini
Labels: Awaiting Review

#113 Remote Data Tutorial
  .travis.yml
  CHANGELOG.rst
  docs/Hangar-Tutorial-003.ipynb
  docs/tutorial.rst
  src/hangar/remotes.py
Labels: documentation

#112 New diff algorithm
  CHANGELOG.rst
  docs/Hangar-Tutorial-002.ipynb
  src/hangar/arrayset.py
  src/hangar/checkout.py
  src/hangar/diff.py
  src/hangar/merger.py
  src/hangar/metadata.py
  src/hangar/records/commiting.py
  src/hangar/records/hashs.py
  src/hangar/records/parsing.py
  src/hangar/records/queries.py
  src/hangar/records/summarize.py
  src/hangar/repository.py
  tests/conftest.py
  tests/test_arrayset.py
  tests/test_diff.py
Labels: Awaiting Review, enhancement
